name: DockerBuild

# Build a multi-arch docker image for Swirl
# comment to start build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: pull latest UI image
        run: docker pull swirlai/spyglass:latest
      - name: builder bootstrap
        run: docker buildx create --name devBuilder --use --bootstrap
      - name: Build the Docker image
        run: docker buildx build -t swirlai/swirl-search:latest --platform linux/amd64,linux/arm64 --push .
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKER_USERNAME_X }}
          password: ${{ secrets.DOCKER_PASSWORD_X }}
          repository: swirlai/swirl-search
